const categories = {
  family: [
    { english: "mother", turkish: "anne" },
    { english: "father", turkish: "baba" },
    { english: "brother", turkish: "erkek kardeş" },
    { english: "sister", turkish: "kız kardeş" },
    { english: "son", turkish: "oğul" },
    { english: "daughter", turkish: "kız evlat" },
    { english: "uncle", turkish: "amca" },
    { english: "aunt", turkish: "hala" },
    { english: "cousin", turkish: "kuzen" },
    { english: "grandparents", turkish: "büyükanne ve büyükbaba" },
  ],
  body: [
    { english: "head", turkish: "baş" },
    { english: "eye", turkish: "göz" },
    { english: "ear", turkish: "kulak" },
    { english: "nose", turkish: "burun" },
    { english: "mouth", turkish: "ağız" },
    { english: "arm", turkish: "kol" },
    { english: "leg", turkish: "bacak" },
    { english: "finger", turkish: "parmak" },
    { english: "foot", turkish: "ayak" },
    { english: "back", turkish: "sırt" },
  ],
  jobs: [
    { english: "doctor", turkish: "doktor" },
    { english: "teacher", turkish: "öğretmen" },
    { english: "engineer", turkish: "mühendis" },
    { english: "lawyer", turkish: "avukat" },
    { english: "nurse", turkish: "hemşire" },
    { english: "chef", turkish: "aşçı" },
    { english: "artist", turkish: "sanatçı" },
    { english: "driver", turkish: "şoför" },
    { english: "scientist", turkish: "bilim insanı" },
    { english: "architect", turkish: "mimar" },
  ],

  food: [
    { english: "apple", turkish: "elma" },
    { english: "banana", turkish: "muz" },
    { english: "bread", turkish: "ekmek" },
    { english: "cheese", turkish: "peynir" },
    { english: "chicken", turkish: "tavuk" },
    { english: "fish", turkish: "balık" },
    { english: "milk", turkish: "süt" },
    { english: "water", turkish: "su" },
  ],

  animals: [
    { english: "dog", turkish: "köpek" },
    { english: "cat", turkish: "kedi" },
    { english: "horse", turkish: "at" },
    { english: "elephant", turkish: "fil" },
    { english: "lion", turkish: "aslan" },
    { english: "tiger", turkish: "kaplan" },
    { english: "rabbit", turkish: "tavşan" },
    { english: "bear", turkish: "ayı" },
  ],

  weather: [
    { english: "sunny", turkish: "güneşli" },
    { english: "rainy", turkish: "yağmurlu" },
    { english: "cloudy", turkish: "bulutlu" },
    { english: "snowy", turkish: "kar yağışlı" },
    { english: "windy", turkish: "rüzgarlı" },
    { english: "stormy", turkish: "fırtınalı" },
    { english: "foggy", turkish: "sisli" },
    { english: "hot", turkish: "sıcak" },
    { english: "cold", turkish: "soğuk" },
    { english: "humid", turkish: "nemli" },
  ],
  furniture: [
    { english: "chair", turkish: "sandalye" },
    { english: "table", turkish: "masa" },
    { english: "sofa", turkish: "koltuk" },
    { english: "bed", turkish: "yatak" },
    { english: "lamp", turkish: "lamba" },
    { english: "cupboard", turkish: "dolap" },
    { english: "shelf", turkish: "raf" },
    { english: "wardrobe", turkish: "gardırop" },
  ],
  color: [
    { english: "red", turkish: "kırmızı" },
    { english: "blue", turkish: "mavi" },
    { english: "green", turkish: "yeşil" },
    { english: "yellow", turkish: "sarı" },
    { english: "orange", turkish: "turuncu" },
    { english: "purple", turkish: "mor" },
    { english: "black", turkish: "siyah" },
    { english: "white", turkish: "beyaz" },
  ],
  clothes: [
    { english: "shirt", turkish: "gömlek" },
    { english: "pants", turkish: "pantolon" },
    { english: "dress", turkish: "elbise" },
    { english: "jacket", turkish: "ceket" },
    { english: "shoes", turkish: "ayakkabı" },
    { english: "socks", turkish: "çorap" },
    { english: "hat", turkish: "şapka" },
    { english: "scarf", turkish: "atkı" },
  ],
  transportation: [
    { english: "car", turkish: "araba" },
    { english: "bus", turkish: "otobüs" },
    { english: "train", turkish: "tren" },
    { english: "airplane", turkish: "uçak" },
    { english: "bike", turkish: "bisiklet" },
    { english: "boat", turkish: "tekne" },
    { english: "ship", turkish: "gemi" },
    { english: "subway", turkish: "metro" },
    { english: "truck", turkish: "kamyon" },
    { english: "taxi", turkish: "taksi" },
    { english: "scooter", turkish: "scooter" },
    { english: "motorcycle", turkish: "motosiklet" },
    { english: "helicopter", turkish: "helikopter" },
    { english: "train station", turkish: "tren istasyonu" },
    { english: "airport", turkish: "havaalanı" },
    { english: "bus station", turkish: "otobüs terminali" },
    { english: "ferry", turkish: "feribot" },
    { english: "parking lot", turkish: "otopark" },
    { english: "ride", turkish: "yolculuk" },
    { english: "trip", turkish: "seyahat" },
  ],
  places: [
    { english: "city", turkish: "şehir" },
    { english: "park", turkish: "park" },
    { english: "beach", turkish: "plaj" },
    { english: "mountain", turkish: "dağ" },
    { english: "forest", turkish: "orman" },
    { english: "restaurant", turkish: "restoran" },
    { english: "market", turkish: "pazar" },
    { english: "school", turkish: "okul" },
    { english: "library", turkish: "kütüphane" },
    { english: "hospital", turkish: "hastane" },
    { english: "stadium", turkish: "stadyum" },
    { english: "museum", turkish: "müze" },
    { english: "theater", turkish: "tiyatro" },
    { english: "airport", turkish: "havaalanı" },
    { english: "mall", turkish: "alışveriş merkezi" },
    { english: "hotel", turkish: "otel" },
    { english: "church", turkish: "kilise" },
    { english: "temple", turkish: "tapınak" },
    { english: "square", turkish: "meydan" },
    { english: "zoo", turkish: "zoo" },
  ],
  emotions: [
    { english: "happy", turkish: "mutlu" },
    { english: "sad", turkish: "üzgün" },
    { english: "angry", turkish: "kızgın" },
    { english: "excited", turkish: "heyecanlı" },
    { english: "scared", turkish: "korkmuş" },
    { english: "nervous", turkish: "sinirli" },
    { english: "surprised", turkish: "şaşırmış" },
    { english: "calm", turkish: "sakin" },
    { english: "bored", turkish: "sıkılmış" },
    { english: "confused", turkish: "karışık" },
    { english: "proud", turkish: "gururlu" },
    { english: "embarrassed", turkish: "utanmış" },
    { english: "guilty", turkish: "suçlu" },
    { english: "hopeful", turkish: "umutlu" },
    { english: "jealous", turkish: "kıskanmış" },
    { english: "grateful", turkish: "minnettar" },
    { english: "lonely", turkish: "yalnız" },
    { english: "relieved", turkish: "rahatlamış" },
    { english: "shy", turkish: "çekingen" },
    { english: "in love", turkish: "aşık" },
  ],
};

let selectedCategory = null;
let level = 1;
let flippedCards = [];
let matchedCards = 0;
let totalCards = 8;
let maxLevel = 6;
let totalPairs = 4;
let totalCorrectMatches = 0;
let wrongMatches = 0;
let score = 0;